services:
  autopoe:
    image: ${AUTOPOE_IMAGE:-imfeh2/autopoe:latest}
    ports:
      - "${AUTOPOE_PORT:-6873}:6873"
    volumes:
      - autopoe-data:/data
    restart: unless-stopped
    init: true

volumes:
  autopoe-data:
